### PR TITLE
feat: move parameter tests into market sim from research internal

### PR DESCRIPTION
**Pull request by TomMcL**
### Description

Dump of Parameter Test code from research-internal into public repo. No major changes other than renaming some folders.

### CODE REVIEW

**Review by Galen-Cao — COMMENTED** [review]
I'm just wondering why not to move the latest parameter-test in research-internal, but it's totally okay to use the origin one if better.

**Comment by TomMcL** [comment]
> I'm just wondering why not to move the latest parameter-test in research-internal, but it's totally okay to use the origin one if better.

This was meant to be a straight dump of the latest code (barring some moving of files about) from research-internal to here. Do you mean I used an old version/missed changes?

**Review by Galen-Cao — DISMISSED** [review]
LGTE

**Review by Galen-Cao — APPROVED** [review]
LGTM

**Pull request merged**
